context:
  version: "0.6.7"

package:
  name: cargo-auditable
  version: ${{ version }}

source:
  url: https://github.com/rust-secure-code/cargo-auditable/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 07641dab34429b7d31ee29bd4f0b426fa486e0be81fce2234d5936d0ba240ee8

build:
  number: 0
  script:
    env:
      CARGO_PROFILE_RELEASE_STRIP: symbols
      CARGO_PROFILE_RELEASE_LTO: fat
    content:
      - if: unix
        then:
          - cargo install --no-track --locked --root ${PREFIX} --path cargo-auditable
          - cargo-bundle-licenses --format yaml --output ${SRC_DIR}/THIRDPARTY.yml
      - if: win
        then:
          - cargo install --no-track --locked --root %PREFIX% --path cargo-auditable
          - if errorlevel 1 exit 1
          - cargo-bundle-licenses --format yaml --output %SRC_DIR%/THIRDPARTY.yml
          - if errorlevel 1 exit 1

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - cargo-bundle-licenses

tests:
  - requirements:
      run:
        - ${{ compiler('rust') }}
    script:
      - cargo auditable --help

about:
  homepage: https://github.com/rust-secure-code/cargo-auditable
  repository: https://github.com/rust-secure-code/cargo-auditable
  documentation: https://github.com/rust-secure-code/cargo-auditable
  summary: Make production Rust binaries auditable
  license: Apache-2.0 OR MIT
  license_file:
    - LICENSE-MIT
    - LICENSE-APACHE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - xhochy
